[BATTERY_CHARGING_CTL]
algo_type monitor
sampling 10000
sensor case-therm-adc
thresholds 51000 52000 53000 54000 55000
thresholds_clr 50000 51000 52000 53000 54000
actions battery battery battery battery battery
action_info 1 2 3 4 5

[CPU_MONITOR]
algo_type monitor
sampling 1000
sensor VIRTUAL-CPU
thresholds 90000
thresholds_clr 85000
actions shutdown
action_info 0

[HIGH_TEMP_STATE]
algo_type monitor
sampling 1000
sensor xo-therm-adc
thresholds 62000
thresholds_clr 60000
actions temp_state
action_info 1

[CCC_AP_TEMP_MITIGATION]
algo_type monitor
sampling 10000
sensor case-therm-adc
thresholds 57000
thresholds_clr 55000
actions temp_state
action_info 5

[SS-CPU7]
algo_type ss
sampling 50
sensor apc1-cpu3-usr
device cpu7
set_point 95000
set_point_clr 55000
time_constant 0

[SS-CPU6]
algo_type ss
sampling 50
sensor apc1-cpu2-usr
device cpu6
set_point 95000
set_point_clr 55000
time_constant 0

[SS-CPU5]
algo_type ss
sampling 50
sensor apc1-cpu1-usr
device cpu5
set_point 95000
set_point_clr 55000
time_constant 0

[SS-CPU4]
algo_type ss
sampling 50
sensor apc1-cpu0-usr
device cpu4
set_point 95000
set_point_clr 55000
time_constant 0

[SS-CPU3]
algo_type ss
sampling 50
sensor apc0-cpu3-usr
device cpu3
set_point 95000
set_point_clr 55000
time_constant 0

[SS-CPU2]
algo_type ss
sampling 50
sensor apc0-cpu2-usr
device cpu2
set_point 95000
set_point_clr 55000
time_constant 0

[SS-CPU1]
algo_type ss
sampling 50
sensor apc0-cpu1-usr
device cpu1
set_point 95000
set_point_clr 55000
time_constant 0

[SS-CPU0]
algo_type ss
sampling 50
sensor apc0-cpu0-usr
device cpu0
set_point 95000
set_point_clr 55000
time_constant 0

[SS-CASE-THERM]
algo_type ss
sampling 10000
sensor case-therm-adc
device cpu0
set_point 54000
set_point_clr 52000
time_constant 0
device_max_limit 1689600

[SS-CASE-THERM-1]
algo_type ss
sampling 10000
sensor case-therm-adc
device cpu0
set_point 54000
set_point_clr 52000
time_constant 0
device_max_limit 1401600

[SS-GPU]
algo_type ss
sampling 250
sensor gpu0-usr
device gpu
set_point 95000
set_point_clr 65000
time_constant 0

[SS-GPU-1]
algo_type ss
sampling 250
sensor gpu1-usr
device gpu
set_point 95000
set_point_clr 65000
time_constant 0

[VIRTUAL-CPU]
algo_type virtual
trip_sensor apc1-cpu0-usr
set_point 75000
set_point_clr 70000
sensors apc1-cpu0-usr apc1-cpu1-usr apc1-cpu2-usr apc1-cpu3-usr apc1-l2-usr
weights
sampling 100
math 2
